### ISSUE TITLE
Allow JWT to be extended by user

### ISSUE THREAD

**Issue by jonny7** [vapor/jwt#125]
As per the discord discussions, logging this here.

There's lots of good and relevant code within JWT, but it's not possible to reuse some key pieces when working with another provider. For example, I'd think it would be nice if you could examine the `Apple+JWT.swift` or `Google+JWT.swift` and then roll your own verifier that extends `Request.JWT` and `Application.JWT`.

If you try to do this though, you'll get inaccessible due to internal protection for some pieces.

```swift
import Vapor
import JWT

extension Request.JWT {
    public var cognito: Cognito{
        .init(request: self.request)
    }

    public struct Cognito{
        let request: Request
     ...
``` 

I believe the same will happen with regards to the `application` property on the extension of `Application.JWT`.

**Comment by tanner0101** [comment]
Related to #124

**Comment by 0xTim** [comment]
@tanner0101 #124 didn't help - it's the `request` property that needs to be made public to allow others to do the same.

@jonny7 I think a PR doing that should be fine

**Comment by tanner0101** [comment]
Yup +1 to exposing request.
