### ISSUE TITLE
Documentation request.

### ISSUE THREAD

**Issue by invencode** [vapor/jwt#126]
I couldn't find documentation on JWT 4.

It would be very helpful if someone provide some documentation or some example codes about Vapor 4 + JWT 4.

**Comment by 0xTim** [comment]
@invencode Yep that's definitely a problem, the reason is because JWT hasn't been released yet. When it is, the docs will be written and finalised. The best place to work out how to use it is the tests

**Comment by tanner0101** [comment]
Docs are now available at https://docs.vapor.codes/4.0/jwt/, thanks!
