### ISSUE TITLE
Token validate is always return True

### ISSUE THREAD

**Issue by Dedy54** [vapor/jwt#14]
HI man, i just newbie from swift and web service, would you tell me why i am always got true on token validate, this is my code 

let jwt = try JWT(payload: Node(ExpirationTimeClaim(Date() + 1)),signer: HS256(key: "secret"))
return try JSON(node: [ "error_code" : "0", "token" : jwt.createToken(), "valid" : "60 second"])

and then i call isValidate like you did : 

let jwt3 = try JWT(token: token)
let isValid = try jwt3.verifySignatureWith(HS256(key: "secret"))
if (isValid==false){
    return try JSON(node: [ "error_code" : "1000", "message" : "Token is expired" ])
}

thanks man

**Comment by siemensikkema** [comment]
Hi @Dedy54. I noticed that before you edited your code you had different keys. Your question seems to imply that even with different keys you got a positive result on the signature verification. In the current version of your code you use the same key so a positive result is expected, no?

There is some extra stuff in your example code not related to the verification of signatures. If I boil it down to the essential part, I get this:

```swift
let jwt = try JWT(payload: [], signer: HS256(key: "secret"))
let token = try jwt.createToken()

let jwt2 = try JWT(token: token)
let isValid = try jwt2.verifySignatureWith(HS256(key: "secret"))
let isNotValid = try jwt2.verifySignatureWith(HS256(key: "terces"))
```
This is as working as expected (tested in a playground). Could your problem be somewhere else in your code? Is there maybe some confusion on the difference between verification of signatures and claims?

**Comment by Dedy54** [comment]
hi @siemensikkema thanks for your answer man, i see, on this case i just did encryption and decryption . and then how about it. On my code i added this parameter 

`payload: Node(ExpirationTimeClaim(Date() + 1)`

its means token will active just for 1 minutes right? or not? but when i try after 1 minutes, this token still active,, its mean true. i did with this code.

`let isValid = try jwt2.verifySignatureWith(HS256(key: "secret"))`

i am did wrong? i am should set myself for token will un active after 1 minutes? what should i do for it? 
thanks @siemensikkema

**Comment by siemensikkema** [comment]
Check out the [`Basic usage`](https://github.com/siemensikkema/vapor-jwt/blob/master/Playground/VaporJWT.playground/Pages/Basic%20usage.xcplaygroundpage/Contents.swift) playground for an explanation.

It comes down to this:
- you should add `60` for a minute
- there's a separate method `verifyClaims`; signature and claims can be verified separately.

**Comment by siemensikkema** [comment]
@Dedy54 I believe this issue is resolved. If there's still something unclear/not working, feel free to open it again.

**Comment by Dedy54** [comment]
thanks @siemensikkema
