### ISSUE TITLE
Version 5.x.x seems to be incompatible with the Apple App Store Server Swift Library

### ISSUE THREAD

**Issue by Eirias** [vapor/jwt#163]
### Describe the issue

The latest version of this repository (vapor/jwt version 5.1.1) appears to be incompatible with the Apple App Store Server Swift Library (app-store-server-library-swift version 2.3.0). This incompatibility is due to conflicting dependencies on different major versions of jwt-kit. The App Store Server Library relies on jwt-kit version 4.x, while vapor/jwt requires jwt-kit version 5.x, leading to a dependency resolution conflict in Swift Package Manager.

### Vapor version

5.x.x

### Operating system and version

15.1.1 (24B91)

### Swift version

Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)

### Steps to reproduce

1.	Create a new Vapor project.
2.	Add the dependency [app-store-server-library-swift](https://github.com/apple/app-store-server-library-swift.git) with version 2.3.0.
3.	Add the dependency [vapor/jwt](https://github.com/vapor/jwt.git) with version 5.1.1.

### Outcome

The dependency resolution behaves inconsistently depending on the order in which dependencies are added to Package.swift.

In this case:
	•	Adding the app-store-server-library-swift dependency first resolves correctly but causes the vapor/jwt dependency to fail resolution.
	•	Conversely, adding vapor/jwt first results in app-store-server-library-swift failing to resolve.

### Additional notes

The issue may tbe caused by both libraries depending on different major versions of [jwt-kit](https://github.com/vapor/jwt-kit.git):
	•	app-store-server-library-swift requires jwt-kit version 4.x.
	•	vapor/jwt requires jwt-kit version 5.x.
	
The Version 4.2.2 works as expected.

**Comment by ptoffy** [comment]
We have https://github.com/apple/app-store-server-library-swift/pull/14 open so this is out of our hands unfortunately

**Comment by gwynne** [comment]
In the meantime, this can be temporarily solved by adding the `jwt` dependency with major version 4.2.2, which will depend on `jwt-kit` 4.x.
