### ISSUE TITLE
Dependency graph could not be satisfied 

### ISSUE THREAD

**Issue by hyouuu** [vapor/jwt#28]
When i add the new vapor/jwt package:
`.Package(url:"https://github.com/vapor/jwt.git", majorVersion: 0)`
to my Package.swift, `vapor xcode` gives error:
`swift-package: error: The dependency graph could not be satisfied (https://github.com/vapor/crypto.git)`
Thoughts?

**Comment by hyouuu** [comment]
Ah I see - jwt 0.9+ uses Vapor 2. nvm

**Comment by bibscy** [comment]
@hyouuu  How did you fix your issue? What "nvm" stands for? My Package.swift looks like this and I get Error: swift-package: error: The dependency graph could not be satisfied (https://github.com/vapor/crypto.git)

import PackageDescription

let package = Package(
    name: "StripePayment",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 1),
        .Package(url:"https://github.com/siemensikkema/vapor-jwt.git", majorVersion: 0)

        
    ],
    exclude: [
        "Config",
        "Database",
        "Localization",
        "Public",
        "Resources",
        "Tests",
    ]
)

**Comment by hyouuu** [comment]
nvm stands for nevermind. I ended up adding a minor: 8 to jwt, because 0.9 up uses Vapor 2

**Comment by bibscy** [comment]
I am trying to push my code to heroku, but I get these errors, do you know how I can fix? Thanks

Bogdans-Air:StripePayment bogdanbarbulescu$ vapor heroku init
Error: Git already has a heroku remote.
Bogdans-Air:StripePayment bogdanbarbulescu$ vapor help
Usage: vapor <new|build|run|fetch|clean|test|xcode|version|self|heroku|docker>
Error: Command "help" not found.
Bogdans-Air:StripePayment bogdanbarbulescu$ vapor heroku -help
Usage: vapor heroku <init|push>
Error: Command "-help" not found.
Bogdans-Air:StripePayment bogdanbarbulescu$ vapor heroku push
Error: spawnProcess
Bogdans-Air:StripePayment bogdanbarbulescu$
