### ISSUE TITLE
build release failure

### ISSUE THREAD

**Issue by tanner0101** [vapor/jwt#29]
This is causing some symbol reference failures when building on Linux in release mode

https://github.com/vapor/jwt/blob/master/Sources/JWT/Claims/TimeBasedClaim.swift#L13

```swift
error: undefined reference to '_TIFE3JWTPS_14TimeBasedClaimcFT10createDateFT_V10Foundation4Date6leewaySi_xA_'
```

**Comment by LoganWright** [comment]
@tanner0101 sometimes these dumb compiler bugs can be worked around by just changing stuff up, does it happen w/o the default arg? What about something like `= { Date($0) }` or some other variant of the default?

Maybe we'll get lucky, I think relying on this getting fixed for 3.1 is a bit of a dream so we should try to get around it if we can

**Comment by tanner0101** [comment]
I worked around for now by using a different init method on the TimeBasedClaim.

**Comment by siemensikkema** [comment]
@tanner0101 is this only on Linux? Does it always happen when building the framework or only when there is code that references the initializer in question?

**Comment by tanner0101** [comment]
@siemensikkema only on linux. it's hard to pin down exactly what causes it... the line linked is fairly complex. It's got `@escaping` closure, default arg, and a Foundation class method. >_<

If i hit it again i will do more debugging.

**Comment by tanner0101** [comment]
Closing this since I have yet to see it again since. Let's hope it was a Swift issue that's been fixed.
