### ISSUE TITLE
How to install using Pod

### ISSUE THREAD

**Issue by DisconnectedPravin** [vapor/jwt#40]
Hi,
How to install using Pod?

Thanks,
Pravin

**Comment by tanner0101** [comment]
For iOS? This package is meant for server side Swift and will probably not work on iOS since it needs to link against OpenSSL.

**Comment by DisconnectedPravin** [comment]
Thank you, I am looking for iOS app to generate the JWT token using RS256.

**Comment by hhanesand** [comment]
@DisconnectedPravin We can't help you here, you're going to have to take a look at some other swift signing frameworks.
