### ISSUE TITLE
Crash in base64 encoder for Swift 3.1 release builds.

### ISSUE THREAD

**Issue by mjmsmith** [vapor/jwt#41]
App crashes in Base64URLTranscoder.base64URLEncode() for release builds only, works fine in Xcode. Crash log attached.

    OS X version: 10.12.4
    Xcode version: 8.3
    Swift version: Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)

Packages.swift:

    .Package(url: "https://github.com/qutheory/vapor.git", majorVersion: 1),
    .Package(url: "https://github.com/vapor/jwt.git", majorVersion: 1),
  
Packages.pins:

    {
      "package": "Vapor",
      "reason": null,
      "repositoryURL": "https://github.com/qutheory/vapor.git",
      "version": "1.5.13"
    },
    {
      "package": "JWT",
      "reason": null,
      "repositoryURL": "https://github.com/vapor/jwt.git",
      "version": "1.0.0"
    },

[App_2017-04-03-162901_fdr.crash.txt](https://github.com/vapor/jwt/files/891331/App_2017-04-03-162901_fdr.crash.txt)

**Comment by tanner0101** [comment]
Thanks for the detailed report. I think moving to vapor/core's base64 encoding will fix this.

If you have time, submitting [this bug to the Swift team](http://bugs.swift.org) as well would be greatly appreciated

**Comment by tanner0101** [comment]
Just looked at this issue. It would be quite an endeavor to fix for Vapor 1. We built our own base64url encoder into Vapor 2 to avoid using Foundation.

As a workaround, I'd try using the non-url Base64Encoder (which uses vapor/core and should work great) and then manually find and replace the `+` and `/` to `-` and `_`

**Comment by vzsg** [comment]
I'm afraid it's not that simple. Base64URLEncoder already does this in 1.0.0: it takes the Base64 encoded string from Core, replaces the characters and trims the padding.

Core 1.1.1 however uses Foundation for Base64 encoding...

**Comment by vzsg** [comment]
Fixed in release 1.0.1.

**Comment by mjmsmith** [comment]
Looks good, no crash here. Thanks!
