### ISSUE TITLE
Allow `IssuedAtClaim` to compare dates

### ISSUE THREAD

**Issue by hhanesand** [vapor/jwt#42]
I'm using Firebase to manage my users, and I use this library to validate `JWT` tokens sent by Firebase. [In their documentation](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library), they state that I must validate that the `Issued-at time` is in the past. I don't think I can do this with the current implementation, as `IssuedAtClaim` forces comparison to a specific time.

**Comment by siemensikkema** [comment]
I had a look at the [jwt spec](https://tools.ietf.org/html/rfc7519) and in section 4.1.6. it does not say anything about how to verify these claims. I now see the implementation I chose does not fit all needs :(
The good news is that you don't have to use the provided claims. What you need is the opposite of NotBeforeClaim so you could copy and adjust the `verify` function and the static `name` variable.

**Comment by hhanesand** [comment]
Ah, ok. Thanks for the response.

Also, thank you for the work you did here! This allowed me to remove a janky Swift + Ruby system I had set in place :)
