### ISSUE TITLE
Shouldn't StringBacked be public ?

### ISSUE THREAD

**Issue by BugsBunnyBR** [vapor/jwt#60]
Would it be useful to have StringBacked as a public Protocol, so a custom claim can be StringBacked?

**Comment by siemensikkema** [comment]
I left StringBacked internal in the recent PR #59 because it did not expose any public extensions. I see your point about creating custom StringBacked claims though. We'd like to rethink the API for the next major release because exposing too many internals as public makes it hard to make changes.
