### ISSUE TITLE
No such module 'JWT', No such module 'JSON'

### ISSUE THREAD

**Issue by tianxuefeng** [vapor/jwt#67]
if open Playground, No such module 'JWT' 
if import swift files to a new project, No such module 'JSON'

Can tell me how to fix these errors? 

Thanks!!!

**Comment by 0xTim** [comment]
@tianxuefeng Swift Package Manager does not support Playgrounds, you need to use SPM to build up your Xcode project

**Comment by tianxuefeng** [comment]
Hello,
Thanks for your reply!
However, I'm getting a error "could not build Objective-C module 'CTLS'"
when run Swift Build command.

Thanks.

#include <openssl/conf.h>
         ^
/Users/Xuefeng/Downloads/jwt-master/.build/checkouts/crypto.git-7980259129511365902/Sources/Crypto/Cipher/Cipher+Method.swift:1:8:
error: could not build Objective-C module 'CTLS'
import CTLS
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/Xuefeng/Downloads/jwt-master/.build/checkouts/ctls.git-9210868160426949823/shim.h:4:10:
error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^
/Users/Xuefeng/Downloads/jwt-master/.build/checkouts/crypto.git-7980259129511365902/Sources/Crypto/Cipher/Cipher+Method.swift:1:8:
error: could not build Objective-C module 'CTLS'
import CTLS
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1):
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool
-f /Users/Xuefeng/Downloads/jwt-master/.build/debug.yaml



Thanks!

Best Regards,
Xuefeng

2017-06-23 5:11 GMT+08:00 Tim <notifications@github.com>:

**Comment by 0xTim** [comment]
@tianxuefeng once you have set up the Vapor Brew Tap (https://docs.vapor.codes/2.0/getting-started/install-on-macos/#add-homebrew-tap) you can do `brew install CTLS` and it should work
