### ISSUE TITLE
IssuedAtClaim should be a TimeBasedClaim rather than an EqualityClaim

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/jwt#69]
`IssuedAtClaim` should be a `TimeBasedClaim` rather than an `EqualityClaim`.

The `verify` method should check that the given value is not in the future.

**Comment by hhanesand** [comment]
https://github.com/vapor/jwt/issues/42

**Comment by tanner0101** [comment]
@siemensikkema is the answer to this the same as to #42?

**Comment by siemensikkema** [comment]
@tanner0101 yes it is. Thanks @hhanesand for reminding me that I answered it before :)

**Comment by valeriomazzeo** [comment]
@siemensikkema what would be the case where it makes sense to verify `iat` by equality rather than by time comparison?

**Comment by siemensikkema** [comment]
@valeriomazzeo Fair question. Maybe we should provide both through an option in the initializer? As mentioned in #42 the spec doesn't say which is the correct way.
Should the time based comparison be the opposite as the NotBeforeClaim?

**Comment by valeriomazzeo** [comment]
>As mentioned in #42 the spec doesn't say which is the correct way.

I can see it's not specified, but I was trying to understand if there is any real world use case where any other kind of comparison different than "time based" can make sense / is useful.

>Should the time based comparison be the opposite as the NotBeforeClaim?

I think so. All we may want to verify is if that token has been issued in the future or not.

**Comment by siemensikkema** [comment]
@valeriomazzeo I actually do not have a good usage for the way it's currently implemented. However, the time-based version would be the exact implementation of `NotBeforeClaim`, not opposite as I first thought. Not before == not in the future.
(sorry for the delay)

**Comment by valeriomazzeo** [comment]
@tanner0101 what action has been taken on this?

**Comment by tanner0101** [comment]
issued at claim uses a date now: https://github.com/vapor/jwt/blob/master/Sources/JWT/JWTClaim.swift#L80
