### ISSUE TITLE
This framework doesn't consider someone may use it in macOS?

### ISSUE THREAD

**Issue by owenzhao** [vapor/jwt#72]
I just got the error message that I don't have `openssl/conf.h` and others.

**Comment by owenzhao** [comment]
Ha, it turns out this requires brew installed ...

Apparently I am not the typical developer who has brew installed ...

**Comment by siemensikkema** [comment]
@owenzhao is your issue solved then? I'm closing the ticket but you can reopen if necessary.

**Comment by owenzhao** [comment]
You can't think it can be closed. However, since I don't want to install brew, I have to not use your framework. =.=

**Comment by vzsg** [comment]
As this library (and most of Vapor) heavily builds upon OpenSSL, you really cannot evade installing it yourself.

**Comment by owenzhao** [comment]
@vssg Maybe you are right. But I say no to brew. I was using it. However, every time macOS upgrades, say from 10.x to 10.x+1, brew will be cleared empty and you have wait many days until it functions again.

 I had never installed brew after being betrayed twice.

**Comment by BrettRToomey** [comment]
All you need to do is link wherever you have your version of openssl installed to: `/usr/local/opt/openssl` and it will work.

**Comment by vzsg** [comment]
Alternatively, you can use the following commands to build your project and generate a working .xcodeproj:

```
# swift build -Xswiftc -I/wherever-openssl-is-installed/include -Xlinker -L/wherever-openssl-is-installed/lib

# swift package -Xswiftc -I/wherever-openssl-is-installed/include -Xlinker -L/wherever-openssl-is-installed/lib generate-xcodeproj
```

**Comment by tanner0101** [comment]
Editing the `/usr/local/lib/pkgconfig/ctls.pc ` to correctly point to your OpenSSL implementation would prevent the need for adding those extra flags to `swift build` and `swift package` commands.
