### ISSUE TITLE
Is this library can be installed using pods?

### ISSUE THREAD

**Issue by dileep017** [vapor/jwt#76]

**Comment by vzsg** [comment]
No. This library depends on Vapor's Crypto module, which in turn depends on OpenSSL – which is not readily available on iOS.

What would you even want to do with this on iOS?
If you are trying to _generate_ tokens, you should really reconsider, as you can make a giant security flaw in your system.
If you just want to _parse_ a token, there is a [better library](https://github.com/auth0/JWTDecode.swift) for your iOS client.

**Comment by dileep017** [comment]
Thanks. I want to generate a token.

**Comment by vzsg** [comment]
Google is our friend: https://github.com/kreactive/JSONWebToken this seems to be a library that depends on CommonCrypto, so should just work on iOS.

**Comment by tanner0101** [comment]
FWIW, I think the 3.0 version of this library (relies on AppleSSL and pure Swift) will work on iOS.
