### ISSUE TITLE
integrate JWTKit with Vapor

### ISSUE THREAD

**Issue by clayellis** [vapor/jwt#88]
Developers who want to create protected routes using JWTs reasonably look towards [Auth](https://github.com/vapor/auth) and to this package (JWT). Currently, though, the two cannot work with one another. Most of the pieces are in place, but they lack an easy-to-use integration layer. 

Auth is the starting point by providing `TokenAuthenticatable` and `TokenAuthenticationMiddleware` which both use an associated `TokenType` which must conform to `Token`. 

This package provides a concrete `JWT` type but since it doesn't conform to `Token` it is ineligible to use currently as a `TokenType`.

I'm not entirely sure what the missing pieces are or should be, but @anthonycastelli shared with me an implementation, that while it didn't leverage the pieces from Auth, does outline a good starting point by creating a `JWTMiddleware` and `JWTService` (as well as an app-specific `JWTPayload` to be used in a `JWT`).

**Comment by clayellis** [comment]
These are the pieces that @anthonycastelli shared with me:

#### `JWTMiddleware`
```swift
import Foundation
import Vapor
import JWT

final class JWTMiddleware: Middleware, Service {
    func respond(to request: Request, chainingTo next: Responder) throws -> Future<Response> {
        guard let authorization = request.http.headers["Authorization"].first,
            let bearer = authorization.split(separator: " ").first,
            let token = authorization.split(separator: " ").last, bearer == "Bearer"
            else { throw Abort(.unauthorized, reason: "No Authorization Header") }
        
        let jwt: JWTService = try request.make()
        let payload = try JWT<JWTAuthPayload>(from: String(token), verifiedUsing: jwt.signer).payload
        guard let userId = UUID(uuidString: payload.userId) else { throw Abort(.unauthorized, reason: "Invalid User") }
        return request.newConnection(to: .psql)
            .flatMap(to: User?.self) { con in
                return try User.find(userId, on: con)
            }.flatMap(to: Response.self) {
                if let u = $0 {
                    try request.authenticate(u)
                }
                _ = try request.requireAuthenticated(User.self)
                return try next.respond(to: request)
        }
    }
}
```

#### `JWTService`
```swift
final class JWTService: Service {
    
    var signer: JWTSigner
    
    init(secret: String) throws {
        self.signer = JWTSigner.hs512(key: Data(secret.utf8))
    }
    
    func signUser<T: CanteenModel>(_ user: T, type: JWTAuthPayload.UserType) throws -> String {
        let expiration = ExpirationClaim(value: Date(timeIntervalSinceNow:(60 * 60 * 1))) // 60 minutes x 1 hour
        var jwt = JWT(payload:
            JWTAuthPayload(
                exp: expiration,
                userId: user.id?.uuidString ?? ""
            )
        )
        let data = try self.signer.sign(&jwt)
        return String(data: data, encoding: .utf8) ?? ""
    }
}
```

#### `JWTAuthPayload`
```swift
struct JWTAuthPayload: JWTPayload {
    enum CodingKeys: String, CodingKey {
        case exp
        case userId = "user_id"
    }
    
    var exp: ExpirationClaim
    var userId: String
    
    func verify() throws {
        try self.exp.verify()
    }
}
```

I think the forthcoming `JWTAuthenticationMiddleware` should leverage `TokenAuthenticationMiddleware` (which in turn leverages `BearerAuthenticationMiddleware`).

**Comment by clayellis** [comment]
Another popular solution that could prove useful as a reference is @calebkleveter's [JWTMiddleware](https://github.com/skelpo/JWTMiddleware).

**Comment by tanner0101** [comment]
This is related to my issue here: https://github.com/vapor/auth/issues/53

**Comment by valeriomazzeo** [comment]
This provides a similar functionality to the old `vapor-community/jwt-provider`: https://github.com/asensei/vapor-auth-jwt

**Comment by nysander** [comment]
Is here any progress to make it work?

**Comment by clayellis** [comment]
Not that I'm aware of. @tanner0101 should we just close this out?

**Comment by tanner0101** [comment]
The idea for Vapor 4 is to create a `vapor/jwt` package that integrates `JWTKit` with `Vapor`. This hasn't been done yet, but should be fairly trivial. I'll leave this issue open to track that.

**Comment by nysander** [comment]
I like this idea to make it core feature

**Comment by tanner0101** [comment]
This package is now a JWTKit + Vapor integration.
