### ISSUE TITLE
[Question] - Encode with RS256 using string data of a private key

### ISSUE THREAD

**Issue by dittmarconsulting** [vapor/jwt#96]
Hi all,

Is it possible to sign a RS256 JWT token with a string of the private keys similar to

```
"-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAtN7LQq7l9a9....SUug==\n-----END RSA PRIVATE KEY-----\n"
```

Many thanks in advance

**Comment by vzsg** [comment]
You can initialize an RSAKey from the PEM-encoded private key using [this initializer](https://github.com/vapor/crypto/blob/master/Sources/Crypto/RSA/RSAKey.swift#L10), which you can then pass to [JWTSigner.rs256](https://github.com/vapor/jwt/blob/master/Sources/JWT/JWTSigner.swift#L97).

**Comment by dittmarconsulting** [comment]
Hi @vzsg,

Thank you for the reply.

I'm not really a iOS developer but I understand the code. Unfortunately my project is written in Objective-C (for React-Native).

Since the project doesn't contain any `.h` header files I created my own bridging header like that:

```
@class RSAKey;
@interface C-RSAKey: NSObject;
- (RSAKey *)returnSwiftObject;
@end
```

Unfortunately I'm stuck here

```
MyRSAKey *rsaKey = [[MyRSAKey alloc] init];
???? public static func `private`(pem: LosslessDataConvertible)
```

Is that possible to use this library in Objective-C at all?

Thanks in advance

**Comment by vzsg** [comment]
This library is for server-side Swift development only, not compatible with iOS (thus React Native) projects at all. What is the use case?

**Comment by dittmarconsulting** [comment]
Hi @vzsg,

I work on a blockchain app in RN. I have a wallet (RSA private/public key) and the JWT token implementation in Android, which was very easy. (JAVA & Javascript is my background)

I'm struggling to find a JWT library for iOS that deals with string form of the private key. According to the research I did, iOS insists to extract the private key from a `.p12` file instead. This library is one of them https://github.com/yourkarma/JWT
